# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/
theme = "congo"

baseURL = "https://www.uniu.net.cn/"
defaultContentLanguage = "zh-Hans"

enableRobotsTXT = true
summaryLength = 0

hasCJKLanguage = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
