languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1
copyright = '<p id="cc-license" xmlns:cc="http://creativecommons.org/ns#">This work © 2025 by <span property="cc:attributionName">WUNIU</span> is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer">CC BY-SA 4.0<img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p>'

title = "Uni's Notitia"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 Jan 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "WUNIU"
  image = "img/avatar.jpg"
  headline = "Be Steady, Patient, and Studious."
  bio = "Who loves everything novel."
  links = [
    { email = "mailto:uniu_admin@icloud.com" },
    { steam = "https://steamcommunity.com/id/Keiki_s_Golem"},
    { littleredbook = "https://www.xiaohongshu.com/user/profile/5fe2dd3e000000000100bd30?xsec_token=YBZMZ3iJxO31YmCYxMaK6DqoYDxX6i7387A0K8XwMRSgM%3D&xsec_source=app_share&xhsshare=CopyLink&appuid=5fe2dd3e000000000100bd30&apptime=1746367579&share_id=016659d372f049d5807e2057598c5f8d&share_channel=copy_link" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/wunewww" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { google-scholar = "https://scholar.google.com/citations?user=user-id" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { mendeley = "https://www.mendeley.com/" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { threads = "https://threads.net/@username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { x-twitter = "https://twitter.com/username" },
  #   { youtube = "https://youtube.com/username" },
  #   { xing = "https://xing.com/profile/username" },
  ]
