baseURL="https://www.wuniu.one"
languageCode = 'en-us'
title = 'wuniu Blog'
theme = 'ananke'
enableRobotsTXT=true
hasCJKLanguage=true
timeZone="Asia/Shanghai"
enableEmoji=true

[Params]
    AuthorName = 'Niu Zhaolong'
    Subtitle = "wuniu's dumb thoughts"
